### ISSUE TITLE
New Install - server digital ocean

### ISSUE THREAD

**Issue by metabona** [HIP-Labs/HIP-Subnet#10]
13|miner_hkp2024H100_36_1  | TRACE:    185.150.27.254:16189 - ASGI [24] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('165.227.xxx.xx', 8091), 'client': ('185.150.27.254', 16189), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/TaskSynapse', 'raw_path': b'/TaskSynapse', 'query_string': b'', 'headers': '<...>', 'state': {}}
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.249 |      TRACE       | axon     | <-- | 13164 B | TaskSynapse | 5CaeumxZb7VBheeNhWHrgxXNrwaoG91h9azykQDqnBWvnW7r | 185.150.27.254:16189 | 200 | Success 
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.250 |      TRACE       | Not Blacklisting recognized hotkey 5CaeumxZb7VBheeNhWHrgxXNrwaoG91h9azykQDqnBWvnW7r
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.251 |      TRACE       | Prioritizing 5CaeumxZb7VBheeNhWHrgxXNrwaoG91h9azykQDqnBWvnW7r with value: 9.999999717180685e-10
13|miner_hkp2024H100_36_1  | TRACE:    185.150.27.254:16189 - ASGI [24] Receive {'type': 'http.request', 'body': '<13032 bytes>', 'more_body': True}
13|miner_hkp2024H100_36_1  | TRACE:    185.150.27.254:16189 - ASGI [24] Receive {'type': 'http.request', 'body': '<132 bytes>', 'more_body': False}
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.331 |      TRACE       | Run exception: Hash mismatch between header body hash df1ae85199923d2ca06edd3a1a0b7127a9cf0bd7e164a4b1a47d6f9bee080888 and parsed body hash e066fdf5b2f227081e183aff1b9bf3184b7721efcd3f4084750218c2a1e054a9
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.334 |      TRACE       | Forward exception: Traceback (most recent call last):
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
13|miner_hkp2024H100_36_1  |     return self.receive_nowait()
13|miner_hkp2024H100_36_1  |            ^^^^^^^^^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
13|miner_hkp2024H100_36_1  |     raise WouldBlock
13|miner_hkp2024H100_36_1  | anyio.WouldBlock
13|miner_hkp2024H100_36_1  | During handling of the above exception, another exception occurred:
13|miner_hkp2024H100_36_1  | Traceback (most recent call last):
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
13|miner_hkp2024H100_36_1  |     return receiver.item
13|miner_hkp2024H100_36_1  |            ^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  | AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'
13|miner_hkp2024H100_36_1  | During handling of the above exception, another exception occurred:
13|miner_hkp2024H100_36_1  | Traceback (most recent call last):
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 78, in call_next
13|miner_hkp2024H100_36_1  |     message = await recv_stream.receive()
13|miner_hkp2024H100_36_1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
13|miner_hkp2024H100_36_1  |     raise EndOfStream
13|miner_hkp2024H100_36_1  | anyio.EndOfStream
13|miner_hkp2024H100_36_1  | During handling of the above exception, another exception occurred:
13|miner_hkp2024H100_36_1  | Traceback (most recent call last):
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/bittensor/axon.py", line 1408, in run
13|miner_hkp2024H100_36_1  |     response = await call_next(request)
13|miner_hkp2024H100_36_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 84, in call_next
13|miner_hkp2024H100_36_1  |     raise app_exc
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 70, in coro
13|miner_hkp2024H100_36_1  |     await self.app(scope, receive_or_disconnect, send_no_error)
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
13|miner_hkp2024H100_36_1  |     raise exc
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
13|miner_hkp2024H100_36_1  |     await self.app(scope, receive, sender)
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
13|miner_hkp2024H100_36_1  |     raise e
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
13|miner_hkp2024H100_36_1  |     await self.app(scope, receive, send)
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
13|miner_hkp2024H100_36_1  |     await route.handle(scope, receive, send)
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/routing.py", line 276, in handle
13|miner_hkp2024H100_36_1  |     await self.app(scope, receive, send)
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/starlette/routing.py", line 66, in app
13|miner_hkp2024H100_36_1  |     response = await func(request)
13|miner_hkp2024H100_36_1  |                ^^^^^^^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/fastapi/routing.py", line 231, in app
13|miner_hkp2024H100_36_1  |     solved_result = await solve_dependencies(
13|miner_hkp2024H100_36_1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 622, in solve_dependencies
13|miner_hkp2024H100_36_1  |     solved = await call(**sub_values)
13|miner_hkp2024H100_36_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/bittensor/axon.py", line 712, in verify_body_integrity
13|miner_hkp2024H100_36_1  |     raise ValueError(
13|miner_hkp2024H100_36_1  | ValueError: Hash mismatch between header body hash df1ae85199923d2ca06edd3a1a0b7127a9cf0bd7e164a4b1a47d6f9bee080888 and parsed body hash e066fdf5b2f227081e183aff1b9bf3184b7721efcd3f4084750218c2a1e054a9
13|miner_hkp2024H100_36_1  | During handling of the above exception, another exception occurred:
13|miner_hkp2024H100_36_1  | Traceback (most recent call last):
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/bittensor/axon.py", line 1068, in dispatch
13|miner_hkp2024H100_36_1  |     response = await self.run(synapse, call_next, request)
13|miner_hkp2024H100_36_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13|miner_hkp2024H100_36_1  |   File "/root/HIP36/venv/lib/python3.12/site-packages/bittensor/axon.py", line 1422, in run
13|miner_hkp2024H100_36_1  |     raise RunException(f"Internal server error with error: {str(e)}")
13|miner_hkp2024H100_36_1  | bittensor.errors.RunException: Internal server error with error: Hash mismatch between header body hash df1ae85199923d2ca06edd3a1a0b7127a9cf0bd7e164a4b1a47d6f9bee080888 and parsed body hash e066fdf5b2f227081e183aff1b9bf3184b7721efcd3f4084750218c2a1e054a9
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.335 |      ERROR       | RunException: Internal server error with error: Hash mismatch between header body hash df1ae85199923d2ca06edd3a1a0b7127a9cf0bd7e164a4b1a47d6f9bee080888 and parsed body hash e066fdf5b2f227081e183aff1b9bf3184b7721efcd3f4084750218c2a1e054a9
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.350 |      TRACE       | axon     | --> | 237 B | TaskSynapse | 5CaeumxZb7VBheeNhWHrgxXNrwaoG91h9azykQDqnBWvnW7r | 185.150.27.254:16189  | 500 | Internal server error with error: Hash mismatch between header body hash df1ae85199923d2ca06edd3a1a0b7127a9cf0bd7e164a4b1a47d6f9bee080888 and parsed body hash e066fdf5b2f227081e183aff1b9bf3184b7721efcd3f4084750218c2a1e054a9
13|miner_hkp2024H100_36_1  | TRACE:    185.150.27.254:16189 - ASGI [24] Send {'type': 'http.response.start', 'status': 500, 'headers': '<...>'}
13|miner_hkp2024H100_36_1  | INFO:     185.150.27.254:16189 - "POST /TaskSynapse HTTP/1.1" 500 Internal Server Error
13|miner_hkp2024H100_36_1  | TRACE:    185.150.27.254:16189 - ASGI [24] Send {'type': 'http.response.body', 'body': '<237 bytes>'}
13|miner_hkp2024H100_36_1  | TRACE:    185.150.27.254:16189 - ASGI [24] Completed
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:01.839 |       INFO       | Miner running... 1718355781.8397622
13|miner_hkp2024H100_36_1  | TRACE:    185.150.27.254:16189 - HTTP connection lost
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:06.840 |       INFO       | Miner running... 1718355786.8406138
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:11.841 |       INFO       | Miner running... 1718355791.8413558
13|miner_hkp2024H100_36_1  | 2024-06-14 09:03:16.842 |       INFO       | Miner running... 1718355796.8425076

**Comment by hamzatrq** [comment]
It just tells that the there's a version mismatch between the validator and the miner. Nothing to worry about just wait for the validators to update to the latest version.
